/*
 * This file is generated by jOOQ.
 */
package cn.linmt.jooq.generate;


import cn.linmt.jooq.generate.tables.Book;


/**
 * Convenience access to all tables in spring_boot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>spring_boot.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
