spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root93633
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      pool-name: jpa-hikari-pool
      max-lifetime: 900000
      maximum-pool-size: 12
      minimum-idle: 8
      connection-test-query: select 1 from dual
      auto-commit: true