/*
 * This file is generated by jOOQ.
 */
package cn.linmt.jooq.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String bookName;
    private Long authorId;
    private Long createdBy;
    private Long modifiedBy;
    private LocalDateTime gmtCreated;
    private LocalDateTime gmtModified;

    public Book() {}

    public Book(Book value) {
        this.id = value.id;
        this.bookName = value.bookName;
        this.authorId = value.authorId;
        this.createdBy = value.createdBy;
        this.modifiedBy = value.modifiedBy;
        this.gmtCreated = value.gmtCreated;
        this.gmtModified = value.gmtModified;
    }

    public Book(
        Long id,
        String bookName,
        Long authorId,
        Long createdBy,
        Long modifiedBy,
        LocalDateTime gmtCreated,
        LocalDateTime gmtModified
    ) {
        this.id = id;
        this.bookName = bookName;
        this.authorId = authorId;
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.gmtCreated = gmtCreated;
        this.gmtModified = gmtModified;
    }

    /**
     * Getter for <code>spring_boot.book.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>spring_boot.book.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>spring_boot.book.book_name</code>. 书名
     */
    public String getBookName() {
        return this.bookName;
    }

    /**
     * Setter for <code>spring_boot.book.book_name</code>. 书名
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * Getter for <code>spring_boot.book.author_id</code>. 作者ID
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>spring_boot.book.author_id</code>. 作者ID
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * Getter for <code>spring_boot.book.created_by</code>. 创建者
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>spring_boot.book.created_by</code>. 创建者
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>spring_boot.book.modified_by</code>. 更新者
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>spring_boot.book.modified_by</code>. 更新者
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>spring_boot.book.gmt_created</code>. 创建时间
     */
    public LocalDateTime getGmtCreated() {
        return this.gmtCreated;
    }

    /**
     * Setter for <code>spring_boot.book.gmt_created</code>. 创建时间
     */
    public void setGmtCreated(LocalDateTime gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * Getter for <code>spring_boot.book.gmt_modified</code>. 更新时间
     */
    public LocalDateTime getGmtModified() {
        return this.gmtModified;
    }

    /**
     * Setter for <code>spring_boot.book.gmt_modified</code>. 更新时间
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Book other = (Book) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.bookName == null) {
            if (other.bookName != null)
                return false;
        }
        else if (!this.bookName.equals(other.bookName))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.gmtCreated == null) {
            if (other.gmtCreated != null)
                return false;
        }
        else if (!this.gmtCreated.equals(other.gmtCreated))
            return false;
        if (this.gmtModified == null) {
            if (other.gmtModified != null)
                return false;
        }
        else if (!this.gmtModified.equals(other.gmtModified))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.bookName == null) ? 0 : this.bookName.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.gmtCreated == null) ? 0 : this.gmtCreated.hashCode());
        result = prime * result + ((this.gmtModified == null) ? 0 : this.gmtModified.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(bookName);
        sb.append(", ").append(authorId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(gmtCreated);
        sb.append(", ").append(gmtModified);

        sb.append(")");
        return sb.toString();
    }
}
