/*
 * This file is generated by jOOQ.
 */
package cn.linmt.jooq.generate.tables.daos;


import cn.linmt.jooq.generate.tables.Book;
import cn.linmt.jooq.generate.tables.records.BookRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookDao extends DAOImpl<BookRecord, cn.linmt.jooq.generate.tables.pojos.Book, ULong> {

    /**
     * Create a new BookDao without any configuration
     */
    public BookDao() {
        super(Book.BOOK, cn.linmt.jooq.generate.tables.pojos.Book.class);
    }

    /**
     * Create a new BookDao with an attached configuration
     */
    public BookDao(Configuration configuration) {
        super(Book.BOOK, cn.linmt.jooq.generate.tables.pojos.Book.class, configuration);
    }

    @Override
    public ULong getId(cn.linmt.jooq.generate.tables.pojos.Book object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Book.BOOK.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchById(ULong... values) {
        return fetch(Book.BOOK.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.linmt.jooq.generate.tables.pojos.Book fetchOneById(ULong value) {
        return fetchOne(Book.BOOK.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<cn.linmt.jooq.generate.tables.pojos.Book> fetchOptionalById(ULong value) {
        return fetchOptional(Book.BOOK.ID, value);
    }

    /**
     * Fetch records that have <code>book_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfBookName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Book.BOOK.BOOK_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>book_name IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchByBookName(String... values) {
        return fetch(Book.BOOK.BOOK_NAME, values);
    }

    /**
     * Fetch records that have <code>author_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfAuthorId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Book.BOOK.AUTHOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>author_id IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchByAuthorId(ULong... values) {
        return fetch(Book.BOOK.AUTHOR_ID, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfCreatedBy(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Book.BOOK.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchByCreatedBy(ULong... values) {
        return fetch(Book.BOOK.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfModifiedBy(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Book.BOOK.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchByModifiedBy(ULong... values) {
        return fetch(Book.BOOK.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>gmt_created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfGmtCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Book.BOOK.GMT_CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>gmt_created IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchByGmtCreated(LocalDateTime... values) {
        return fetch(Book.BOOK.GMT_CREATED, values);
    }

    /**
     * Fetch records that have <code>gmt_modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchRangeOfGmtModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Book.BOOK.GMT_MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>gmt_modified IN (values)</code>
     */
    public List<cn.linmt.jooq.generate.tables.pojos.Book> fetchByGmtModified(LocalDateTime... values) {
        return fetch(Book.BOOK.GMT_MODIFIED, values);
    }
}
